conjuctions = ['and',
'or',
'but',
'nor',
'so',
'for',
'yet',
'after',
'although',
'as',
'as',
'if',
'as',
'long',
'as',
'because',
'before',
'even',
'if',
'even',
'though',
'once',
'since',
'so',
'that',
'though',
'till',
'unless',
'until',
'what',
'when',
'whenever',
'wherever',
'whether' 
'while']

prepositions = ['aboard',
'about',
'above',
'across',
'after',
'against',
'along',
'amid',
'among',
'anti',
'around',
'as',
'at',
'before',
'behind',
'below',
'beneath',
'beside',
'besides',
'between',
'beyond',
'but',
'by',
'concerning',
'considering',
'despite',
'down',
'during',
'except',
'excepting',
'excluding',
'following',
'for',
'from',
'in',
'inside',
'into',
'like',
'minus',
'near',
'of',
'off',
'on',
'onto',
'opposite',
'outside',
'over',
'past',
'per',
'plus',
'regarding',
'round',
'save',
'since',
'than',
'through',
'to',
'toward',
'towards',
'under',
'underneath',
'unlike',
'until',
'up',
'upon',
'versus',
'via',
'with',
'within',
'without']

pronouns = ['all',
'another',
'any',
'anybody',
'anyone',
'anything',
'both',
'each',
'each',
'either',
'everybody',
'everyone',
'everything',
'few',
'he',
'her',
'hers',
'herself',
'him',
'himself',
'his',
'i',
'it',
'its',
'itself',
'little',
'many',
'me',
'mine',
'more',
'most',
'much',
'my',
'myself',
'neither',
'no',
'nobody',
'none',
'nothing',
'one',
'one',
'other',
'others',
'our',
'ours',
'ourselves',
'several',
'she',
'some',
'somebody',
'someone',
'something',
'that',
'their',
'theirs',
'them',
'themselves',
'these',
'they',
'this',
'those',
'we',
'what',
'whatever',
'which',
'whichever',
'who',
'whoever',
'whom',
'whomever',
'whose',
'you',
'your',
'yours',
'yourself',
'yourselves']

ordinals = ['rd', 'st', 'th']

months = ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december']

omit_verbs = ['is', 'was', 'am', 'were', 'are', 'will', 'be', 'have', 'had', 'has']

omit_words = ['a', 'an', 'the', 'hi', 'dear', 'sir', 'madam', 'mam', 'respected', 'team', 'hyundai']

interjections = ['aha',
'ahem',
'ahh',
'ahoy',
'alas',
'arg',
'aw',
'bam',
'bingo',
'blah',
'boo',
'bravo',
'ang',
'drat',
'darn',
'duh',
'eek',
'eh',
'encore',
'eureka',
'fiddlesticks',
'gadzooks',
'gee',
'gee whiz',
'golly',
'goodbye',
'goodness',
'good grief',
'gosh',
'ha-ha',
'hallelujah',
'hello',
'hey',
'hmm',
'holy buckets',
'holy cow',
'holy smokes',
'hot dog',
'huh',
'humph',
'hurray',
'oh',
'oh dear',
'oh my',
'oh well',
'oops',
'ouch',
'ow',
'phew',
'phooey',
'pooh',
'pow',
'shh',
'shoo',
'thanks',
'there',
'tut-tut',
'uh-huh',
'uh-oh',
'ugh',
'wahoo',
'well',
'whoa',
'whoops',
'wow',
'yeah',
'yes',
'yikes',
'yippee',
'yo',
'yuck']


car_parts = ['bonet', 'bonnet', 'bonnet/hood',
'bonnet/hood latch',
'bumper',
'unexposed bumper',
'exposed bumper',
'compressor',
'cowl screen',
'decklid',
'fascia rear and support',
'fender (wing or mudguard)',
'front clip',
'front fascia and header panel',
'grille (also called grill)',
'pillar and hard trim',
'quarter panel',
'radiator core support',
'rocker panel',
'roof rack',
'spoiler',
'front spoiler (air dam)',
'rear spoiler (wing)',
'rims',
'hubcap',
'tire',
'tyre',
'trim package',
'trunk/boot/hatch',
'trunk/boot latch',
'valance',
'welded assembly',
'outer door handle',
'inner door handle',
'door control module',
'door seal',
'door watershield',
'hinge',
'door latch',
'door lock and power door locks',
'center-locking',
'fuel tank (or fuel filler) door',
'glass',
'sunroof',
'sunroof motor',
'window motor',
'window regulator',
'windshield (also called windscreen)',
'windshield washer motor',
'window seal',
'antenna assembly',
'antenna cable',
'radio and media player',
'other devices',
'speaker',
'tuner',
'subwoofer',
'alternator',
'alternator bearing',
'alternator bracket',
'alternator fan',
'other alternator parts',
'battery',
'performance battery',
'battery box',
'battery cable terminal',
'battery cable',
'battery control system',
'battery plate',
'battery tray',
'voltage regulator',
'ammeter',
'clinometer',
'dynamometer',
'fuel gauge',
'hydrometer',
'odometer (also called milometer or mileometers)',
'speedometer',
'tachometer (also called rev counters)',
'temperature gauge',
'tire pressure gauge',
'vacuum gauge',
'voltmeter',
'water temperature meter',
'coil wire',
'distributor',
'electronic timing controller',
'ignition box',
'ignition coil',
'ignition coil parts',
'ignition magneto',
'spark plug',
'engine bay lighting',
'fog light (also called foglamp)',
'halogen',
'headlight (also called headlamp)',
'headlight motor',
'interior light and lamp',
'license plate lamp (also called number plate lamp or registration plate lamp)',
'side lighting',
'tail light',
'tail light cover',
'airbag sensors',
'automatic transmission speed sensor',
'camshaft position sensor',
'coolant temperature sensor',
'crankshaft position sensor',
'engine sensor',
'fuel level sensor',
'fuel pressure sensor',
'knock sensor',
'light sensor',
'oil level sensor',
'oil pressure sensor',
'mass flow sensor',
'starter',
'starter drive',
'starter motor',
'starter solenoid',
'glowplug',
'battery',
'door switch',
'ignition switch',
'power window switch',
'steering column switch',
'switch cover',
'switch panel',
'thermostat',
'frame switch',
'parts and functions of starter system',
'ac',
'conditioner',
'a.c.'
'air conditioning harness',
'engine compartment harness',
'interior harness',
'main harness',
'floor harness',
'control harness',
'air bag control module',
'alarm and siren',
'central locking system',
'chasis'
'chassis'
'chassis control computer',
'cruise control computer',
'door contact',
'engine computer and management system',
'engine control unit',
'fuse',
'fuse box',
'ground strap',
'grab handle (aka "oh s***" handle)',
'performance chip',
'performance monitor',
'relay connector',
'remote lock',
'shift improver',
'speed controller',
'speedometer calibrator',
'transmission computer',
'wiring connector',
'dash panels',
'carpet and other floor material',
'center console (front and rear)',
'trap (secret compartment)',
'arm rest',
'bench seat',
'bucket seat',
'children and baby car seat',
'fastener',
'headrest',
'seat belt',
'seat bracket',
'seat cover',
'seat track',
'other seat components',
'anti-lock braking system (abs)',
'abs',
'abs steel pin',
'adjusting mechanism (adjuster star wheel)',
'anchor',
'bleed nipple',
'brake backing plate',
'brake backing pad',
'brake cooling duct',
'brake disc',
'brake drum',
'brake line/cable',
'brake pad',
'brake pedal',
'brake piston',
'brake pump',
'brake roll',
'brake rotor',
'brake servo',
'brake shoe',
'brake lining',
'brake',
'shoe web',
'brake warning light',
'calibrated friction brake',
'caliper',
'combination valve',
'dual circuit brake system',
'hold-down springs (retainer springs)',
'hose',
'brake booster hose',
'air brake nylon hose',
'brake duct hose',
'hydraulic booster unit',
'load-sensing valve',
'master cylinder',
'metering valve',
'braking',
'park brake lever/handle (hand brake)',
'pressure differential valve',
'proportioning valve',
'reservoir',
'shoe return spring',
'tyre',
'vacuum brake booster',
'wheel cylinder (slave cylinder)',
'wheel stud',
'engine'
'diesel engine',
'petrol engine',
'gasoline engine',
'accessory belt',
'air duct',
'air intake housing',
'air intake manifold',
'camshaft',
'camshaft bearing',
'camshaft fastener',
'camshaft follower',
'camshaft locking plate',
'camshaft pushrod',
'camshaft spacer ring',
'connecting rod',
'connecting rod bearing',
'connecting rod bolt',
'connecting rod washer',
'crank case',
'crank pulley',
'crankshaft',
'crankshaft oil seal',
'cylinder head',
'cylinder head cover',
'other cylinder head cover parts',
'cylinder head gasket',
'distributor',
'distributor cap',
'drive belt',
'engine block',
'engine block',
'engine cradle',
'engine shake damper and vibration absorber',
'engine valve',
'fan belt',
'gudgeon pin (wrist pin)',
'harmonic balancer',
'heater',
'mounting',
'piston',
'piston pin and crank pin',
'piston pin bush',
'piston ring and circlip',
'poppet valve',
'pcv valve (positive crankcase ventilation valve)',
'pulley part',
'rocker arm',
'rocker cover',
'starter motor',
'motor'
'starter pinion',
'starter ring',
'steering',
'turbocharger and supercharger',
'tappet',
'timing tape',
'valve cover',
'valve housing',
'valve spring',
'valve stem seal',
'water pump pulley',
'air blower',
'coolant hose (clamp)',
'cooling fan',
'fan blade',
'clutch'
'fan clutch',
'radiator',
'radiator bolt',
'radiator (fan) shroud',
'radiator gasket',
'radiator pressure cap',
'overflow tank',
'water neck',
'water neck o-ring',
'water pipe',
'water pump',
'water pump gasket',
'water tank',
'oil filter',
'oil gasket',
'oil pan',
'oil pipe',
'oil pump',
'oil strainer',
'catalytic converter',
'exhaust clamp and bracket',
'exhaust flange gasket',
'exhaust gasket',
'exhaust manifold',
'exhaust manifold gasket',
'exhaust pipe',
'heat shield',
'heat sleeving and tape',
'resonator',
'muffler (silencer)',
'spacer ring',
'ely',
'air filter',
'carburetor',
'carburetor parts',
'choke cable',
'egr valve',
'fuel cap',
'fuel cell',
'fuel cell component',
'fuel cooler',
'fuel distributor',
'fuel filter',
'fuel filter seal',
'fuel injector',
'fuel injector nozzle',
'fuel pump',
'fuel pump gasket',
'fuel pressure regulator',
'fuel rail',
'fuel tank',
'fuel tank cover',
'fuel water separator',
'intake manifold',
'intake manifold gasket',
'lpg (liquefied petroleum gas) system assembly',
'throttle body',
'beam axle',
'control arm',
'constant-velocity axle',
'constant-velocity joint',
'idler arm',
'kingpin',
'panhard rod',
'pitman arm',
'power steering assembly and component',
'rack end',
'shock absorber',
'spindle',
'spring',
'air spring',
'coil spring',
'leaf and parabolic leaf spring',
'rubber spring',
'spiral spring',
'stabilizer bars and link',
'steering arm',
'steering box',
'steering column assembly',
'steering rack (a form of steering gear; see also rack and pinion and recirculating ball)',
'steering shaft',
'steering wheel (driving wheel)',
'strut',
'stub axle',
'suspension link and bolt',
'tie bar',
'tie rod',
'tie rod end',
'trailing arm',
'adjustable pedal',
'axle shaft',
'bell housing',
'cam belt',
'other belts',
'carrier assembly',
'chain wheel and sprocket',
'clutch assembly',
'clutch cable',
'clutch disk',
'clutch fan',
'clutch fork',
'clutch hose',
'clutch lever',
'clutch lining',
'clutch pedal',
'clutch pressure plate',
'clutch shoe',
'clutch spring',
'differential',
'differential case',
'pinion bearing',
'differential clutch',
'spider gears',
'differential casing',
'differential flange',
'differential gear',
'differential seal',
'flywheel',
'flywheel ring gear',
'gear',
'gearbox',
'gear coupling',
'gear pump',
'gear ring',
'gear stick (gearstick',
'gear lever',
'selection lever',
'shift stick',
'gear shifter)',
'gearbox',
'idler gear',
'knuckle',
'master cylinder',
'output shaft',
'pad',
'pinion',
'planetary gear set',
'prop shaft (drive shaft',
'propeller shaft',
'seat',
'sensors',
'shift cable',
'shift fork',
'shift knob',
'shift lever',
'slave cylinder',
'speed reducer',
'speedometer gear',
'steering gear',
'torque converter',
'transaxle housing',
'transfer case',
'transmission gear',
'transmission pan',
'transmission seal and bonded piston',
'transmission spring',
'transmission yolk',
'universal joint (uj',
' cardan joint)',
'a/c clutch',
'a/c compressor',
'a/c condenser',
'a/c hose',
'a/c kit',
'a/c relay',
'a/c valve',
'a/c expansion valve',
'a/c low-pressure valve',
'a/c schrader valve',
'a/c inner plate',
'a/c cooler',
'a/c evaporator',
'ball joint',
'grooved ball bearing',
'needle bearing',
'roller bearing',
'sleeve bearing',
'fuel vapour hose',
'reinforced hose (high-pressure hose)',
'non-reinforced hose',
'washer hose',
'adhesive tape and foil',
'air bag',
'bolt cap',
'bracket (aluminium',
' iron',
' and magnesium bracket)',
'license plate bracket',
'cables',
'speedometer cable',
'cotter pin',
'decal',
'dashboard',
'center console',
'glove compartment',
'drag link',
'dynamic seal',
'fastener',
'gasket: flat',
'moulded',
'profiled',
'hood and trunk release cable',
'horn and trumpet horn',
'injection-molded parts',
'injector',
'instrument cluster',
'label',
'mirror',
'mount and mounting',
'name plate',
'nut',
'flange nut',
'hex nut',
'o-ring',
'paint',
'rivet',
'rubber (extruded and molded)',
'screw',
'shim',
'sun visor',
'wiper',
'viper',
'washer']

service_related_words = ['service', 'servicing', 'staff', 'repair', 'harassment', 'showroom', 'center', 'manager', 'centre', 'services', 'executive', 'delay', 'cheating', 'shop', 'dealers', 'employees', 'representative', 'technician']

damage_related_words = ['damage', 'abnormal', 'issue', 'overheating', 'parts', 'mileage', 'alignment']

negative_words = ['fooled', 'fake', 'complaint', 'fraud', 'disappointed', 'disappointment', 'unsatisfied']
